"""create shows table

Revision ID: 45938f780a4e
Revises: af810890bb8f
Create Date: 2026-09-05 20:24:06.908668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45938f780a4e'
down_revision: Union[str, Sequence[str], None] = 'af810890bb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section', sa.Enum('FEATURED', 'SERIES', 'MINISODES', 'SONGS', name='show_section'), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_is_published'), 'shows', ['is_published'], unique=False)
    op.create_index(op.f('ix_shows_section'), 'shows', ['section'], unique=False)
    op.create_index(op.f('ix_shows_slug'), 'shows', ['slug'], unique=True)
    op.create_index(op.f('ix_shows_title'), 'shows', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_title'), table_name='shows')
    op.drop_index(op.f('ix_shows_slug'), table_name='shows')
    op.drop_index(op.f('ix_shows_section'), table_name='shows')
    op.drop_index(op.f('ix_shows_is_published'), table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
