"""create publish runs table

Revision ID: 87f5889f6d76
Revises: 6a166cce52be
Create Date: 2026-09-05 22:02:59.601880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f5889f6d76'
down_revision: Union[str, Sequence[str], None] = '6a166cce52be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('catalogue_path', sa.String(length=1000), nullable=True),
    sa.Column('show_count', sa.Integer(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_runs_status'), 'publish_runs', ['status'], unique=False)
    op.create_index(op.f('ix_publish_runs_triggered_by'), 'publish_runs', ['triggered_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publish_runs_triggered_by'), table_name='publish_runs')
    op.drop_index(op.f('ix_publish_runs_status'), table_name='publish_runs')
    op.drop_table('publish_runs')
    # ### end Alembic commands ###
